export const OPEN_MODEL = "OPEN_MODEL"
export const CLOSE_MODEL = "CLOSE_MODEL"

export const SIGN_OPEN = "SIGN_OPEN"
export const SIGN_CLOSE = "SIGN_CLOSE"


export const FETCH_REQUEST = "FETCH_REQUEST"
export const FETCH_SUCCESS = "FETCH_SUCCESS"
export const FETCH_FAILURE = "FETCH_FAILURE"

export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILURE = "LOGIN_FAILURE"

export const SIGN_REQUEST = "SIGN_REQUEST"
export const SIGN_SUCCESS = "SIGN_SUCCESS"
export const SIGN_FAILURE = "SIGN_FAILURE"

export const ADD_TO_CART= "ADD_TO_CART"
export const REMOVE_TO_CART= "REMOVE_TO_CART"
export const INCREMENT = "INCREMENT"
export const DECREMENT = "DECREMENT"
export const TOTAL = "TOTAL"
export const DATADETAILS= "DATADETAILS"
export const LOGINDETAILS= "LOGINDETAILS"
export const SIGNUPDETAILS = "SIGNUPDETAILS"

export const SELLER_REQUEST = "SELLER_REQUEST"
export const SELLER_SUCCESS = "SELLER_SUCCESS"
export const SELLER_FAILURE = "SELLER_FAILURE"

export const LOGIN_SELLER_REQUEST ="LOGIN_SELLER_REQUEST"
export const LOGIN_SELLER_SUCCESS ="LOGIN_SELLER_SUCCESS"
export const LOGIN_SELLER_FAILURE ="LOGIN_SELLER_FAILURE"

export const FETCH_SELLER_REQUEST="FETCH_SELLER_REQUEST"
export const FETCH_SELLER_SUCCESS="FETCH_SELLER_SUCCESS"
export const FETCH_SELLER_FAILURE="FETCH_SELLER_FAILURE"

export const ADD_PRODUCT_REQUEST ="ADD_PRODUCT_REQUEST"
export const ADD_PRODUCT_SUCCESS ="ADD_PRODUCT_SUCCESS"
export const ADD_PRODUCT_FAILURE ="ADD_PRODUCT_FAILURE"


export const LOGIN_ADMIN_REQUEST ="[admin-login] LOGIN_ADMIN_REQUEST"
export const LOGIN_ADMIN_SUCCESS ="[admin-login] LOGIN_ADMIN_SUCCESS"
export const LOGIN_ADMIN_FAILURE ="[admin-login] LOGIN_ADMIN_FAILURE"